import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cat Facts Middleware Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Catfacts Challenge
        </h1>

        <p className={styles.description}>
          A quick API for getting Cat Facts. Please try the following endpoints:
        </p>

        <div className={styles.grid}>

          <a href="/api/facts" target="_blank" className={styles.card}>
            <h2>All available facts (unsorted) &rarr;</h2>
            <p>
              /api/facts
            </p>
          </a>

          <a href="/api/facts?page=2&per_page=5" target="_blank" className={styles.card}>
            <h2>Get paginated facts &rarr;</h2>
            <p>
              /api/facts?page=2&per_page=5
            </p>
          </a>

          <a href="/api/facts?sort=alphabetic" target="_blank" className={styles.card}>
            <h2>All facts sorted alphabetically &rarr;</h2>
            <p>
              /api/facts?sort=alphabetic
            </p>
          </a>

          <a href="/api/facts?page=12&per_page=10&sort=alphabetic" target="_blank" className={styles.card}>
            <h2>Get paginated facts with alphabetic sorting &rarr;</h2>
            <p>
              /api/facts?page=12&per_page=10&sort=alphabetic
            </p>
          </a>

          <a href="/api/fact/10" target="_blank" className={styles.card}>
            <h2>Get single fact by ID &rarr;</h2>
            <p>
              /api/fact/10
            </p>
          </a>

          <a href="/api/facts?sort=length_ascending" target="_blank" className={styles.card}>
            <h2>Get all facts sorted by length ascending &rarr;</h2>
            <p>
              /api/facts?sort=length_ascending
            </p>
          </a>

          <a href="/api/facts?page=5&per_page=20&sort=length_ascending" target="_blank" className={styles.card}>
            <h2>Get paginated facts sorted by length ascending &rarr;</h2>
            <p>
              /api/facts?page=5&per_page=20&sort=length_ascending
            </p>
          </a>

          <a href="/api/facts?sort=length_descending" target="_blank" className={styles.card}>
            <h2>Get all facts sorted by length descending &rarr;</h2>
            <p>
              /api/facts?sort=length_descending
            </p>
          </a>

          <a href="/api/facts?page=4&per_page=15&sort=length_descending" target="_blank" className={styles.card}>
            <h2>Get paginated facts sorted by length descending &rarr;</h2>
            <p>
              /api/facts?page=4&per_page=15&sort=length_ascending
            </p>
          </a>

          <a href="/api/facts?sort=reverse_alphabetic" target="_blank" className={styles.card}>
            <h2>All facts sorted in reverse alphabetic order &rarr;</h2>
            <p>
              /api/facts?sort=reverse_alphabetic
            </p>
          </a>

          <a href="/api/facts?page=12&per_page=10&sort=reverse_alphabetic" target="_blank" className={styles.card}>
            <h2>Get paginated facts in reverse alphabetic order &rarr;</h2>
            <p>
              /api/facts?page=12&per_page=10&sort=reverse_alphabetic
            </p>
          </a>

        </div>
      </main>
    </div>
  )
}

export default Home
