import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Cat Facts Middleware Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Catfacts Challenge
        </h1>

        <p className={styles.description}>
          A quick API for getting Cat Facts. Please try the following endpoints:
        </p>

        <div className={styles.grid}>

          <a href="/api/facts" target="_blank" className={styles.card}>
            <h2>All available facts &rarr;</h2>
            <p>
              /api/facts
              <br/><br/>
            </p>
          </a>

          <a href="/api/facts?page=2&per_page=5" target="_blank" className={styles.card}>
            <h2>Get paginated facts &rarr;</h2>
            <p>
              /api/facts?page=2<br/>&per_page=5
            </p>
          </a>

          <a href="/api/fact/10" target="_blank" className={styles.card}>
            <h2>Get fact by ID &rarr;</h2>
            <p>
              /api/fact/10
              <br/><br/>
            </p>
          </a>

        </div>
      </main>
    </div>
  )
}

export default Home
